import ProjectDetailsSection from "../project-details/ProjectDetailsSection";

const AizawlContent = `To support the Indian Railways’ ongoing efforts toward environmental sustainability and waste management, Endlos Innovations partnered with East Central Railway's Danapur Division for the deployment of PET bottle shredding machines across key railway stations in Bihar. The initiative aimed to reduce plastic waste generated by passengers and promote a cleaner transit environment. Under this project, we successfully supplied and installed 15 PET Bottle Shredder Machines across 15 railway stations, including prominent junctions like Patna, Danapur, Buxar, and Ara. Each machine was engineered to meet railway-grade specifications, ensuring safe disposal of plastic waste through high-efficiency shredding mechanisms. The machines were tested, certified, and handed over in working condition after thorough inspection and approval from station authorities.

Designed for durability and performance, the machines include features such as powder-coated steel enclosures, hardened special alloy cutters, auto motor shut-off for safety, and noise reduction systems. These shredders can process up to 25 kg of PET waste per hour, contributing significantly to the reduction of single-use plastics within railway premises. With CE and NABL certifications, our solution met all government compliance standards, ensuring long-term reliability. The project was delivered on schedule and acknowledged as satisfactory by the division’s environmental and engineering teams, reinforcing our position as a trusted partner for public infrastructure and sustainability solutions.
`;

export default function AizawlProjectPage() {
  return (
    <ProjectDetailsSection
      title="Patna, Bihar Railway Plastic Waste Initiative"
      logoUrl="/assets/images/image.png"
      logoImgURL="https://bspcb.bihar.gov.in/"
      imageUrl="/assets/images/rvm/Patna_project_inside.png"
      bgimg="/assets/images/rvm/Patna_project_outside.png"
      description={AizawlContent}
    />
  );
}
